version: '3'

services:

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks: 
      - dockernet
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on: 
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks: 
      - dockernet
  
  nginx:
    build:
      context: nginx
    container_name: nginx
    networks: 
      - dockernet
    ports:
      - "8080:80"

networks: 
  dockernet:
    driver: bridge